name: Compliance
on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  coding-standard:
    name: PSR-12 coding standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install PHP code sniffer
        run: composer global require squizlabs/php_codesniffer

      - name: Check against PSR12 standard
        run: |
          `composer global config bin-dir --absolute --quiet`/phpcs --standard=PSR12 ./src

  tests:
    name: PHP [${{ matrix.php }}] - Lumen [${{ matrix.lumen }}]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [  8.0, 8.1 ]
        lumen: [ 9, 10 ]
        exclude:
          - php: 8.1
            lumen: 8
          - php: 8.1
            lumen: 9
          - php: 8.0
            lumen: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: |
          composer require illuminate/support:^${{ matrix.lumen }} --no-interaction --prefer-dist

      - name: Run test suite
        run: ./vendor/bin/phpunit --testdox --verbose tests/
