name: tests
on:
  pull_request:
  push:
    branches:
      - main
      - '*.x'

jobs:
  tests:
    name: PHP [${{ matrix.php }}] - Lumen [${{ matrix.lumen }}]
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1, 8.2]
        lumen: [9, 10]
        exclude:
          - php: 8.0
            lumen: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: |
          composer require laravel/lumen:^${{ matrix.lumen }} --no-interaction --prefer-dist
          composer update --prefer-dist --no-interaction --no-progress

      - name: Run test suite
        run: vendor/bin/phpunit --testdox --verbose
